### ISSUE TITLE
0.12 support

### ISSUE THREAD

**Issue by marcusramberg** [tweag/terraform-provider-secret#2]
Would be great if this plugin could be updated with 0.12 support. 

```
Error: failed to load provider "secret": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

I tried updating the vendor dep to open a PR, but apparently my go-fu isn't strong enough.

**Comment by zimbatm** [comment]
do you mind testing master? I updated the deps in https://github.com/tweag/terraform-provider-secret/pull/3 but don't have terraform 0.12 installed to test it out

**Comment by marcusramberg** [comment]
Thanks, that works great :)
